---
- include_vars: "samba_host_{{ ansible_os_family }}_vars.yml"

- import_tasks: "samba_host_RedHat_tasks.yml"
  when: ansible_os_family == "RedHat"

  # TODO
  # Add usershares, printers, home directories
  # "lmhosts" in name resolve order
  # logging options
  # "include" share parameter available. Split and tidy smb.conf template?
