---
- include_vars: "samba_host_{{ ansible_distribution }}_vars.yml"

- import_tasks: "samba_host_CentOS_tasks.yml"
  when: ansible_distribution == "CentOS"

  # TODO
  # Add usershares, printers, home directories
  # "lmhosts" in name resolve order
  # logging options
  # "include" share parameter available. Split and tidy smb.conf template?
